### ISSUE TITLE
Library is using "babel-runtime", but doesn't have it in dependency list

### ISSUE THREAD

**Issue by lkatartn** [jcoreio/react-router-transition-switch#5]
I've removed babel from my project and saw that this library requires 'babel-runtime'. It is not in the list of dependencies (and peer dependencies also).  Also it is not in the source code, because babel adds it during transpiling.

**Comment by jedwards1211** [comment]
Oh good catch, my bad!  Looks like this repo is still on Babel 6 too, I'll upgrade and fix the deps shortly.

**Comment by lkatartn** [comment]
Thank you, that is not obvious thing, because almost everybody uses Babel now
